[build]
  command = "CI='' yarn build"
  publish = "start"

[build.environment]
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--production=false"

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
